### ISSUE TITLE
DB Proxy Identifier is Difficult to Access for Granting IAM

### ISSUE THREAD

**Issue by chrisoverzero** [aws-cloudformation/aws-cloudformation-resource-providers-rds-proxy#23]
One of the attributes of an `AWS::RDS::DBProxy` is its `DBProxyArn`. In order to grant permission via IAM to `rds-db:connect` to a DB Proxy, we have to chop up that ARN like this:

```yaml
Statement:
  Effect: Allow
  Action: rds-db:connect
  Resource: !Sub
  - arn:${AWS::Partition}:rds-db:${AWS::Region}:${AWS::AccountId}:dbuser:${Id}/${UserName}
  - Id: !Select
    - 6 # note(cosborn) 0-indexed, arn:PARTITION:rds:REGION:ACCOUNT:db-proxy:IDENTIFIER
    - !Split [ ':', !GetAtt Proxy.DBProxyArn ]
    UserName: !FindInMap [ Database, !Ref Environment, UserName ]
```

It's error-prone and unnecessarily verbose to do this over and again for each connecting role. It would be better if the… say, `DBProxyId` were exposed directly as an attribute on the proxy.

Alternatively, the attribute name could be:

- `DBProxyIdentifier`
- `DBProxyId`
- `DBProxyResourceId` (the documentation seems to call out the equivalent ID on a DB instance as the "Resource ID")
- `Id` (though probably not, for whatever reasons `Arn` became `DBProxyArn`)
